import pandas as pd
import numpy as np

df = pd.read_csv('smart_grid_dataset_sylhet.csv')
print('=== DATASET OVERVIEW ===')
print(f'Shape: {df.shape}')
print(f'Columns: {list(df.columns)}')
print(f'Upazilas: {df["upazila"].nunique()}')
print(f'Date range: {df["datetime"].min()} to {df["datetime"].max()}')
print()
print('=== MISSING VALUES ===')
print(df.isnull().sum())
print()
print('=== DUPLICATES ===')
print(f'Duplicate rows: {df.duplicated().sum()}')
print()
print('=== CLASS DISTRIBUTION ===')
print(df['risk_level'].value_counts())
print((df['risk_level'].value_counts(normalize=True).round(4) * 100).astype(str) + '%')
print()
print('=== FEATURE STATISTICS ===')
print(df[['temperature','humidity','rainfall','demand_index']].describe())
print()
df['datetime'] = pd.to_datetime(df['datetime'])
df_sorted = df.sort_values('datetime')
split = int(len(df_sorted) * 0.8)
train_end = df_sorted.iloc[split-1]['datetime']
test_start = df_sorted.iloc[split]['datetime']
print(f'=== SPLIT BOUNDARY ===')
print(f'Train ends: {train_end}')
print(f'Test starts: {test_start}')
print(f'Overlap: {train_end >= test_start}')
print()
print('=== UNIQUE UPZILAS ===')
print(df['upazila'].unique())
print()

# Check for target leakage indicators
print('=== TARGET LEAKAGE CHECKS ===')
print('demand_index vs risk_level correlation:')
print(df[['demand_index','risk_level']].groupby('risk_level')['demand_index'].agg(['mean','min','max']).round(4))